// react-app/src/shared/components/UIElements/Map.js
import React, { useRef, useEffect } from 'react'

import './Map.css'

const Map = props => {

  const mapRef = useRef()
  const { center, zoom } = props;

  useEffect(() => {
    const map = new window.google.maps.Map(mapRef.current, {
      center: center,
      zoom: zoom
    })
    new window.google.maps.Marker({ position: center, map: map })
  }, [center, zoom])



  return (
    <div
      ref={mapRef}
      className={`map ${props.className}`}
      style={props.style}>
    </div>
  )
}

export default Map

// vue-app/src/shared/components/UIElements/Map.vue
<template>
  <div ref="mapRef" :class="['map', mapClass]" :style="style"></div>
</template>

<script>
export default {
  props: ["mapClass", "style", "center", "zoom"],
  data() {
    return {
      map: null
    };
  },
  methods: {
    loadMap() {
      this.map = new window.google.maps.Map(this.$refs.mapRef, {
        center: this.$props.center,
        zoom: +this.$props.zoom
      });
      new window.google.maps.Marker({
        position: this.$props.center,
        map: this.map
      });
    }
  },
  mounted() {
    this.loadMap();
  }
};
</script>

<style>
.map {
  width: 100%;
  height: 100%;
}
</style>
