// vue-app/src/places/components/PlaceItem.vue
<template>
  <the-modal
    @onCancel="closeMapHandler"
    v-if="showMap"
    :show="showMap"
    contentClass="place-item__modal-content"
    footerClass="place-item__modal-actions"
  >
    <template v-slot:header>
      {{ $props.address }}
    </template>
    <template v-slot:default>
      <div class="map-container">
        <Map :center="coordinates" zoom="16" />
      </div>
    </template>
    <template v-slot:footer>
      <the-button @click="closeMapHandler">CLOSE</the-button>
    </template>
  </the-modal>
  <the-modal
    v-if="showConfirmModal"
    :show="showConfirmModal"
    @onCancel="cancelDeleteHandler"
    footerClass="place-item__modal-actions"
  >
    <template v-slot:header>
      Are you sure?
    </template>
    <p>Please click Confirm to Delete. This cannot be undone.</p>
    <template v-slot:footer>
      <the-button inverse="inverse" @click="cancelDeleteHandler"
        >Cancel</the-button
      >
      <the-button danger="danger" type="button" @click="confirmDeleteHandler"
        >Delete</the-button
      >
    </template>
  </the-modal>
  <li class="place-item">
    <the-card class="place-item__content">
      <div class="place-item__image">
        <img :src="image" :alt="title" />
      </div>
      <div class="place-item__info">
        <h2>{{ title }}</h2>
        <h3>{{ address }}</h3>
        <p>{{ description }}</p>
      </div>
      <div class="place-item__actions">
        <the-button inverse="inverse" @click="openMapHandler"
          >View on Map</the-button
        >
        <the-button v-if="$store.getters.isLoggedIn" :to="'/places/' + id"
          >Edit</the-button
        >
        <the-button
          v-if="$store.getters.isLoggedIn"
          @click="showDeleteWarningHandler"
          danger="danger"
          >Delete</the-button
        >
      </div>
    </the-card>
  </li>
</template>

<script>
import { ref } from "vue";
import Map from "../../shared/components/UIElements/Map";
export default {
  components: { Map },
  props: {
    id: {
      type: String
    },
    title: {
      type: String
    },
    image: {
      type: String
    },
    address: {
      type: String
    },
    description: {
      type: String
    },
    creatorId: {
      type: String
    },
    coordinates: {
      type: Object
    }
  },
  setup() {
    const showMap = ref(false);
    const showConfirmModal = ref(false);

    const openMapHandler = () => {
      showMap.value = true;
    };
    const closeMapHandler = () => {
      showMap.value = false;
    };

    const showDeleteWarningHandler = () => {
      showConfirmModal.value = true;
    };

    const cancelDeleteHandler = () => {
      showConfirmModal.value = false;
    };

    const confirmDeleteHandler = () => {
      console.log("DELETE");
      showConfirmModal.value = false;
    };

    return {
      showMap,
      showConfirmModal,
      openMapHandler,
      closeMapHandler,
      showDeleteWarningHandler,
      cancelDeleteHandler,
      confirmDeleteHandler
    };
  }
};
</script>

<style>
.place-item {
  margin: 1rem 0;
}

.place-item__content {
  padding: 0;
}

.place-item__info {
  padding: 1rem;
  text-align: center;
}

.place-item__image {
  width: 100%;
  height: 12.5rem;
  margin-right: 1.5rem;
}

.place-item__image img {
  width: 100%;
  height: 100%;
  object-fit: cover;
}

.place-item__info h2,
.place-item__info h3,
.place-item__info p {
  margin: 0 0 0.5rem 0;
}

.place-item__actions {
  padding: 1rem;
  text-align: center;
  border-top: 1px solid #ccc;
}

.place-item__modal-content {
  padding: 0;
}

.place-item__modal-actions {
  text-align: right;
}

.place-item__actions button,
.place-item__actions a {
  margin: 0.5rem;
}

.map-container {
  height: 15rem;
  width: 100%;
}

@media (min-width: 768px) {
  .place-item__image {
    height: 20rem;
  }
}
</style>

// react-app/src/places/components/PlaceItem.js
import React, { useState, useContext } from 'react';

import Card from '../../shared/components/UIElements/Card';
import Button from '../../shared/components/FormElements/Button';
import Modal from '../../shared/components/UIElements/Modal';
import Map from '../../shared/components/UIElements/Map';
import { AuthContext } from '../../shared/context/auth-context';

import './PlaceItem.css';

const PlaceItem = (props) => {
	const auth = useContext(AuthContext);

	const [showMap, setShowMap] = useState(false);
	const [showConfirmModal, setShowConfirmModal] = useState(false);

	const openMapHandler = () => setShowMap(true);
	const closeMapHandler = () => setShowMap(false);

	const showDeleteWarningHandler = () => {
		setShowConfirmModal(true);
	};

	const cancelDeleteHandler = () => {
		setShowConfirmModal(false);
	};

	const confirmDeleteHandler = () => {
		setShowConfirmModal(false);
		console.log('DELETE');
	};

	return (
		<React.Fragment>
			<Modal
				show={showMap}
				onCancel={closeMapHandler}
				header={props.address}
				contentClass='place-item__modal-content'
				footerClass='place-item__modal-actions'
				footer={<Button onClick={closeMapHandler}>CLOSE</Button>}
			>
				<div className='map-container'>
					<Map center={props.coordinates} zoom={16} />
				</div>
			</Modal>
			<Modal
				show={showConfirmModal}
				onCancel={cancelDeleteHandler}
				header='Are you sure?'
				footerClass='place-item__modal-actions'
				footer={
					<React.Fragment>
						<Button inverse onClick={cancelDeleteHandler}>
							Cancel
						</Button>
						<Button danger onClick={confirmDeleteHandler}>
							Delete
						</Button>
					</React.Fragment>
				}
			>
				<p>Please click Confirm to delete. This cannot be undone.</p>
			</Modal>
			<li className='place-item'>
				<Card className='place-item__content'>
					<div className='place-item__image'>
						<img src={props.image} alt={props.title} />
					</div>
					<div className='place-item__info'>
						<h2>{props.title}</h2>
						<h3>{props.address}</h3>
						<p>{props.description}</p>
					</div>
					<div className='place-item__actions'>
						<Button inverse onClick={openMapHandler}>
							View On Map
						</Button>
						{auth.isLoggedIn && (
							<Button to={'/places/' + props.id}>Edit</Button>
						)}
						{auth.isLoggedIn && (
							<Button danger onClick={showDeleteWarningHandler}>
								Delete
							</Button>
						)}
					</div>
				</Card>
			</li>
		</React.Fragment>
	);
};

export default PlaceItem;
