// vue-app/src/places/components/PlaceList.vue
<template>
  <div v-if="userPlaces.length === 0" class="place-list center">
    <the-card>
      <h2>No places found. Create One?</h2>
      <the-button to="/places/new">Share Place</the-button>
    </the-card>
  </div>
  <ul class="place-list">
    <place-item
      v-for="place in userPlaces"
      :key="place.id"
      :id="place.id"
      :image="place.imageUrl"
      :title="place.title"
      :description="place.description"
      :address="place.address"
      :creatorId="place.creator"
      :coordinates="place.location"
    ></place-item>
  </ul>
</template>

<script>
import PlaceItem from "./PlaceItem";
export default {
  components: { PlaceItem },
  props: ["userPlaces"]
};
</script>

<style>
.place-list {
  list-style: none;
  margin: 1rem auto;
  padding: 0;
  width: 90%;
  max-width: 40rem;
}
</style>

// react-app/src/places/components/PlaceList.js
import React from 'react'

import Card from '../../shared/components/UIElements/Card'
import PlaceItem from './PlaceItem'
import './PlaceList.css'


const PlaceList = props => {
  if (props.items.length === 0) {
    return <div className="place-list center">
      <Card>
        <h2>No places found. Create One?</h2>
        <button>Share Place</button>
      </Card>
    </div>
  }

  return (
    <ul className="place-list">
      {props.items.map(place => (
        <PlaceItem
          key={place.id}
          id={place.id}
          image={place.imageUrl}
          title={place.title}
          description={place.description}
          address={place.address}
          creatorId={place.creator}
          coordinates={place.location}
        />
      )
      )}
    </ul>
  )

}

export default PlaceList
