// vue-app/src/users/components/UsersList.vue
<template>
  <ul class="users-list">
    <user-item
      v-for="user in users"
      :key="user.id"
      :id="user.id"
      :name="user.name"
      :image="user.image"
      :placeCount="user.places"
    ></user-item>
  </ul>
</template>

<script>
import UserItem from "./UserItem.vue";

export default {
  props: {
    users: {
      type: Array,
    },
  },
  components: { UserItem },
};
</script>

<style>
.users-list {
  list-style: none;
  margin: 0 auto;
  padding: 0;
  width: 90%;
  max-width: 50rem;
  display: flex;
  justify-content: center;
  flex-wrap: wrap;
}
</style>

// react-app/src/user/components/UsersList.js
import React from 'react'

import UserItem from './UserItem'
import Card from '../../shared/components/UIElements/Card'

import './UsersList.css'


const UsersList = props => {

  if (props.items.length === 0) {
    return <div className="center">
      <Card>
        <h2>No users found</h2>
      </Card>
    </div>
  }

  return (
    <ul className="users-list">
      {props.items.map(user => {
        return (
          <UserItem
            key={user.id}
            id={user.id}
            image={user.image}
            name={user.name}
            placeCount={user.places}
          />
        )
      })}
    </ul>
  )
}

export default UsersList
