// vue-app/src/user/pages/Auth.vue
<template>
  <the-error-modal
    v-if="errorMessage"
    :errorMessage="errorMessage"
    @click="clearError"
  ></the-error-modal>
  <the-card class="authentication">
    <the-loading-spinner v-if="isLoading" :asOverlay="true">
    </the-loading-spinner>
    <h2>Login Required</h2>
    <hr />
    <form @submit.prevent="authSubmitHandler">
      <the-input
        v-if="!isLoginMode"
        id="name"
        element="input"
        type="text"
        label="Your name"
        :validators="[validatorRequired()]"
        errorText="Please enter name."
        @onInput="inputHandler"
      ></the-input>
      <image-upload
        v-if="!isLoginMode"
        center="center"
        id="image"
        @onInput="inputHandler"
      ></image-upload>
      <the-input
        id="email"
        element="input"
        type="email"
        label="Email"
        :validators="[validatorEmail()]"
        errorText="Please enter valid email."
        @onInput="inputHandler"
      ></the-input>
      <the-input
        id="password"
        element="input"
        type="password"
        label="Password"
        :validators="[validatorMinlegth(6)]"
        errorText="Please enter valid password, min legth 6 characters."
        @onInput="inputHandler"
      ></the-input>
      <the-button type="submit" :disabled="!formData.isValid">{{
        isLoginMode ? "Login" : "Signup"
      }}</the-button>
      <the-button type="button" inverse="inverse" @click="switchModeHandler"
        >Switch to {{ isLoginMode ? "Signup" : "Login" }}</the-button
      >
    </form>
  </the-card>
</template>

<script>
import { ref } from "vue";
import { useRouter } from "vue-router";
import { useStore } from "vuex";
import { useForm } from "../../shared/hooks/form-hook";
import { useHttp } from "../../shared/hooks/http-hook";

import ImageUpload from "../../shared/components/FormElements/ImageUpload";

import {
  VALIDATOR_EMAIL,
  VALIDATOR_MINLENGTH,
  VALIDATOR_REQUIRE
} from "../../shared/utils/validator";

export default {
  components: { ImageUpload },
  setup() {
    const isLoginMode = ref(true);
    const { isLoading, errorMessage, sendRequest, clearError } = useHttp();

    const [formData, inputHandler, setFormData] = useForm(
      {
        email: {
          value: "",
          isValid: false
        },
        password: {
          value: "",
          isValid: false
        }
      },
      false
    );

    const switchModeHandler = () => {
      if (!isLoginMode.value) {
        setFormData(
          {
            ...formData.inputs,
            name: undefined,
            image: undefined
          },
          formData.inputs.email.isValid && formData.inputs.password.isValid
        );
      } else {
        setFormData(
          {
            ...formData.inputs,
            name: {
              value: "",
              isValid: false
            },
            image: {
              value: null,
              isValid: false
            },
            isValid: false
          },
          false
        );
      }
      isLoginMode.value = !isLoginMode.value;
    };

    const store = useStore();
    const router = useRouter();

    const authSubmitHandler = async () => {
      if (isLoginMode.value) {
        try {
          const url = "http://localhost:5500/api/users/login";

          const userData = await sendRequest(
            url,
            "POST",
            JSON.stringify({
              email: formData.inputs.email.value,
              password: formData.inputs.password.value
            }),
            { "Content-Type": "application/json" }
          );

          store.dispatch("login", userData.user._id);
          router.push("/");
        } catch (error) {
          console.log(error.message);
        }
      } else {
        try {
          const url = "http://localhost:5500/api/users/signup";

          const data = new FormData();
          data.append("email", formData.inputs.email.value);
          data.append("name", formData.inputs.name.value);
          data.append("password", formData.inputs.password.value);
          data.append("image", formData.inputs.image.value);

          const userData = await sendRequest(url, "POST", data);

          store.dispatch("login", userData.user._id);
          router.push("/");
        } catch (error) {
          console.log(error.message);
        }
      }
    };

    const validatorEmail = () => VALIDATOR_EMAIL();
    const validatorMinlegth = val => VALIDATOR_MINLENGTH(val);
    const validatorRequired = () => VALIDATOR_REQUIRE();

    return {
      isLoading,
      errorMessage,
      isLoginMode,
      formData,
      switchModeHandler,
      authSubmitHandler,
      inputHandler,
      clearError,
      validatorEmail,
      validatorMinlegth,
      validatorRequired
    };
  }
};
</script>

<style>
.authentication__header {
  color: white;
  text-align: center;
}

.authentication {
  width: 90%;
  max-width: 25rem;
  margin: 7rem auto;
  text-align: center;
}

.authentication form {
  margin-bottom: 1rem;
}
</style>

// react-app/src/user/pages/Auth.js
import React, { useState, useContext, Fragment } from 'react';

import Card from '../../shared/components/UIElements/Card';
import Input from '../../shared/components/FormElements/Input';
import Button from '../../shared/components/FormElements/Button';
import ErrorModal from '../../shared/components/UIElements/ErrorModal';
import LoadingSpinner from '../../shared/components/UIElements/LoadingSpinner';
import ImageUpload from '../../shared/components/FormElements/ImageUpload';

import {
	VALIDATOR_EMAIL,
	VALIDATOR_MINLENGTH,
	VALIDATOR_REQUIRE,
} from '../../shared/utils/validator';

import { useForm } from '../../shared/hooks/form-hook';
import { useHttp } from '../../shared/hooks/http-hook';
import { AuthContext } from '../../shared/context/auth-context';

import './Auth.css';

const Auth = () => {
	const auth = useContext(AuthContext);
	const [isLoginMode, setIsLoginMode] = useState(true);
	const { isLoading, errorMessage, sendRequest, clearError } = useHttp();

	const [formState, inputHandler, setFormData] = useForm(
		{
			email: {
				value: '',
				isValid: false,
			},
			password: {
				value: '',
				isValid: false,
			},
		},
		false,
	);

	const switchModeHandler = () => {
		if (!isLoginMode) {
			setFormData(
				{
					...formState.inputs,
					name: undefined,
					image: undefined,
				},
				formState.inputs.email.isValid && formState.inputs.password.isValid,
			);
		} else {
			setFormData(
				{
					...formState.inputs,
					name: {
						value: '',
						isValid: false,
					},
					image: {
						value: null,
						isValid: false,
					},
					isValid: false,
				},
				false,
			);
		}
		setIsLoginMode((prevMode) => !prevMode);
	};

	const authSubmitHandler = async (event) => {
		event.preventDefault();

		if (isLoginMode) {
			try {
				const url = 'http://localhost:5500/api/users/login';
				const resData = await sendRequest(
					url,
					'POST',
					JSON.stringify({
						email: formState.inputs.email.value,
						password: formState.inputs.password.value,
					}),
					{
						'Content-Type': 'application/json',
					},
				);
				auth.login(resData.user._id);
			} catch (error) {
				console.log(error.message);
			}
		} else {
			try {
				const url = 'http://localhost:5500/api/users/signup';

				const formData = new FormData();
				formData.append('email', formState.inputs.email.value);
				formData.append('name', formState.inputs.name.value);
				formData.append('password', formState.inputs.password.value);
				formData.append('image', formState.inputs.image.value);

				const resData = await sendRequest(url, 'POST', formData);
				auth.login(resData.user._id);
			} catch (error) {
				console.log(error.message);
			}
		}
	};

	return (
		<Fragment>
			<ErrorModal error={errorMessage} onClear={clearError} />
			<Card className='authentication'>
				{isLoading && <LoadingSpinner asOverlay />}
				<h2>Login Required</h2>
				<hr />
				<form onSubmit={authSubmitHandler}>
					{!isLoginMode && (
						<Input
							id='name'
							element='input'
							type='text'
							label='Your Name'
							validators={[VALIDATOR_REQUIRE()]}
							errorText='Pleae enter a name.'
							onInput={inputHandler}
						/>
					)}
					{!isLoginMode && (
						<ImageUpload
							center
							id='image'
							onInput={inputHandler}
							errorText='Please provide an image.'
						/>
					)}
					<Input
						id='email'
						element='input'
						type='email'
						label='Email'
						validators={[VALIDATOR_EMAIL()]}
						errorText='Pleae enter a valid email'
						onInput={inputHandler}
					/>
					<Input
						id='password'
						element='input'
						type='password'
						label='Password'
						validators={[VALIDATOR_MINLENGTH(6)]}
						errorText='Pleae enter a password with at least 6 characters.'
						onInput={inputHandler}
					/>
					<Button type='submit' disabled={!formState.isValid}>
						{isLoginMode ? 'Login' : 'Signup'}
					</Button>
					<Button type='button' inverse onClick={switchModeHandler}>
						Switch to {isLoginMode ? 'Signup' : 'Login'}
					</Button>
				</form>
			</Card>
		</Fragment>
	);
};

export default Auth;
