// vue-app/src/user/pages/Users.vue
<template>
  <the-error-modal
    v-if="errorMessage"
    :errorMessage="errorMessage"
    @click="clearError"
  ></the-error-modal>
  <div class="center">
    <the-loading-spinner v-if="isLoading" :asOverlay="true">
    </the-loading-spinner>
  </div>
  <users-list :users="users"></users-list>
</template>

<script>
import { ref } from "vue";
import UsersList from "../components/UsersList";
import { useHttp } from "../../shared/hooks/http-hook";

export default {
  components: { UsersList },
  setup() {
    const users = ref([]);
    const { isLoading, errorMessage, sendRequest, clearError } = useHttp();

    const getUsers = async () => {
      const url = "http://localhost:5500/api/users";
      try {
        const userData = await sendRequest(url);
        users.value = userData.users;
      } catch (error) {
        console.log(error.message);
      }
    };

    getUsers();
    return { users, isLoading, errorMessage, clearError };
  }
};
</script>

// react-app/src/user/pages/Users.js
import React, { useEffect, useState } from 'react';

import UsersList from '../components/UsersList';
import ErrorModal from '../../shared/components/UIElements/ErrorModal';
import LoadingSpinner from '../../shared/components/UIElements/LoadingSpinner';

import { useHttp } from '../../shared/hooks/http-hook';

const Users = () => {
	const { isLoading, errorMessage, sendRequest, clearError } = useHttp();
	const [loadedUsers, setLoadedUsers] = useState();

	useEffect(() => {
		const getUsers = async () => {
			const url = 'http://localhost:5500/api/users';
			try {
				const userData = await sendRequest(url);
				setLoadedUsers(userData.users);
			} catch (error) {
				console.log(error.message);
			}
		};
		getUsers();
	}, [sendRequest]);

	return (
		<React.Fragment>
			<ErrorModal error={errorMessage} onClear={clearError} />
			{isLoading && (
				<div className='center'>
					<LoadingSpinner />
				</div>
			)}
			{!isLoading && loadedUsers && <UsersList items={loadedUsers} />}
		</React.Fragment>
	);
};

export default Users;
