// vue-app/src/places/pages/NewPlace.vue
<template>
  <form class="place-form" @submit.prevent="placeSubmitHandler">
    <the-input
      id="title"
      element="input"
      type="text"
      label="Title"
      :validators="[validatorRequire()]"
      errorText="Please enter a valid title"
      @onInput="inputHandler"
    ></the-input>
    <the-input
      id="description"
      element="textarea"
      label="Description"
      :validators="[validatorMinLength(5)]"
      errorText="Please enter a valid description (at least 5 characters)."
      @onInput="inputHandler"
    ></the-input>
    <the-input
      id="address"
      element="input"
      label="Address"
      :validators="[validatorRequire()]"
      errorText="Please enter a valid address."
      @onInput="inputHandler"
    ></the-input>
    <the-button type="submit" :disabled="!formState.isValid"
      >Add Place</the-button
    >
  </form>
</template>

<script>
import {
  VALIDATOR_REQUIRE,
  VALIDATOR_MINLENGTH
} from "../../shared/utils/validator";

import { useForm } from "../../shared/hooks/form-hook";

import "./PlaceForm.css";

export default {
  setup() {
    const [formState, inputHandler] = useForm(
      {
        title: {
          value: "",
          isValid: false
        },
        description: {
          value: "",
          isValid: false
        },
        address: {
          value: "",
          isValid: false
        }
      },
      false
    );

    const validatorRequire = () => VALIDATOR_REQUIRE();
    const validatorMinLength = val => VALIDATOR_MINLENGTH(val);

    const placeSubmitHandler = () => {
      console.log(formState.inputs);
    };

    return {
      validatorRequire,
      validatorMinLength,
      inputHandler,
      formState,
      placeSubmitHandler
    };
  }
};
</script>

// react-app/src/places/pages/NewPlace.js
import React from 'react';

import Input from '../../shared/components/FormElements/Input';
import Button from '../..//shared/components/FormElements/Button';

import {
	VALIDATOR_MINLENGTH,
	VALIDATOR_REQUIRE,
} from '../../shared/utils/validator';

import { useForm } from '../../shared/hooks/form-hook';

import './PlaceForm.css';

const NewPlace = () => {
	const [formState, inputHandler] = useForm(
		{
			title: {
				value: '',
				isValid: false,
			},
			description: {
				value: '',
				isValid: false,
			},
			address: {
				value: '',
				isValid: false,
			},
		},
		false,
	);

	const placeSubmitHandler = (event) => {
		event.preventDefault();
		console.log(formState.inputs);
	};

	return (
		<form className='place-form' onSubmit={placeSubmitHandler}>
			<Input
				id='title'
				element='input'
				type='text'
				label='Title'
				validators={[VALIDATOR_REQUIRE()]}
				errorText='Please enter a valid title'
				onInput={inputHandler}
			/>
			<Input
				id='description'
				element='textarea'
				label='Description'
				validators={[VALIDATOR_MINLENGTH(5)]}
				errorText='Please enter a valid description (at least 5 characters).'
				onInput={inputHandler}
			/>
			<Input
				id='address'
				element='input'
				label='Address'
				validators={[VALIDATOR_REQUIRE()]}
				errorText='Please enter a valid address.'
				onInput={inputHandler}
			/>
			<Button type='submit' disabled={!formState.isValid}>
				Add Place
			</Button>
		</form>
	);
};

export default NewPlace;
